title                    : "Boyan Wan (万博岩)"
title_separator          : "-"
description              : "Direct-entry Ph.D. track at Zhejiang University | Crop Science | Plant Stress Biology"
url                      : "https://fushan-emd.github.io"
baseurl                  : ""
repository               : "fushan-emd/fushan-emd.github.io"
locale                   : "en-US"
timezone                 : "Asia/Shanghai"

google_scholar_stats_use_cdn : false
google_analytics_id      :
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

author:
  name             : "Boyan Wan (万博岩)"
  avatar           : "images/profile.webp"
  bio              : "Zhejiang University"
  location         : "Hangzhou, China"
  employer         :
  email            :
  github           : "fushan-emd"
  googlescholar    :
  pubmed           :
  researchgate     :
  linkedin         :
  dblp             :
  orcid            :
  uri              :
  twitter          :
  facebook         :
  instagram        :
  weibo            :
  youtube          :

include:
  - .htaccess
  - _pages
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
